### ISSUE TITLE
Fork influxdb role so we have ownership

### ISSUE THREAD

**Issue by jsmartin** [jsmartin/lightbulb#49]

**Comment by tima** [comment]
Started: https://github.com/tima/ansible-role-influxdb

**Comment by jsmartin** [comment]
Awesome, looks like you had a commit in there, might as well use that as our starting point.

**Comment by tima** [comment]
I hadn't updated my personal fork since before the holidays. I made one PR
back then that that made it in since my last pull tho so I just merged my
local branch in to get that.

On Thursday, February 4, 2016, James S. Martin <notifications@github.com>
wrote:

> Awesome, looks like you had a commit in there, might as well use that as
> our starting point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsmartin/lightbulb/issues/49#issuecomment-180074285>.
>


-- 

[image: photo]
Timothy Appnel
Senior Architect

Ansible, Inc. *•* www.ansible.com
